language: node_js
cache:
  directories:
  - node_modules
node_js:
- 8.9
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g npm@^3.0.0
install:
- npm install
script:
- npm run lint
- npm run build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  keep-history: true
  github-token: 59b49498b13fbca2a9e69ae0d59c194576691c70
  on:
    branches:
      only:
        - master
