language: node_js
cache:
  directories:
  - node_modules
node_js:
- 8.9
install:
- npm install
script:
- npm run lint
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: 59b49498b13fbca2a9e69ae0d59c194576691c70
  local-dir: dist
  on:
    branches:
      only:
        - master
