language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '8'
install:
- npm install
script:
- npm run lint
- npm run build

deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    github-token: $GITHUB_API_KEY
    local-dir: dist
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
