language: node_js
cache:
  directories:
  - node_modules
node_js:
- 8.9
install:
- npm install
script:
- npm run lint
- npm run build

# TODO: make deploy work
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_API_KEY
  local-dir: dist
  on:
    branch: master
