language: node_js
cache:
  directories:
  - node_modules
node_js:
- 8.9
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g npm@^3.0.0
install:
- npm install
script:
- npm run lint
- npm run build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  keep-history: true
  github-token: "205af607223b7f2b88ca47bb7a53a58f520823cf"
  on:
    branches:
      only:
        - master
